# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('patronymic', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', '\u043c\u0443\u0436\u0441\u043a\u043e\u0439'), ('F', '\u0436\u0435\u043d\u0441\u043a\u0438\u0439'), ('N', '\u043d\u0435 \u0443\u043a\u0430\u0437\u0430\u043d')], default='N', max_length=1)),
                ('birthday', models.DateField()),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('building', models.CharField(max_length=5)),
                ('apartment', models.PositiveSmallIntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactBook.City')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactBook.Job'),
        ),
        migrations.AddField(
            model_name='contact',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactBook.Post'),
        ),
        migrations.AddField(
            model_name='contact',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contactBook.Street'),
        ),
    ]
